### ISSUE TITLE
CI/CD to build and publish aar automatically.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/java-libkiwix#11]
we must developed CI/CD to build and publish aar automatically.

**Comment by kelson42** [comment]
@mgautierfr what is the status here?

**Comment by MohitMaliFtechiz** [comment]
@kelson42, We have developed the CI to automatically publish the `.aar` file and we have successfully published the `.aar` file on the Maven via our CI, so now we can close this ticket.
https://github.com/kiwix/java-libkiwix/actions/runs/5530436701/jobs/10089835798
