### ISSUE TITLE
Maven publishcation of java-libkiwix failed.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/java-libkiwix#111]
There is a failure to upload the `java-libkiwix` on Maven. See https://github.com/kiwix/java-libkiwix/actions/runs/9825608936/job/27125971728.

We have to change the `OSSRH_USERNAME` and `OSSRH_PASSWORD` with tokens in github env. See the latest changes https://community.sonatype.com/t/401-content-access-is-protected-by-token-authentication-failure-while-performing-maven-release/12741/7, here are the steps on how we can generate the token https://central.sonatype.org/publish/generate-token/

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please ahare with me which secrets I shoukd configure in github and do the rest of the changes

**Comment by MohitMaliFtechiz** [comment]
We have updated the token in our secrets, and now CD has started uploading the artifact on Maven(https://github.com/kiwix/java-libkiwix/actions/runs/9825608936) so closing this issue.
