### ISSUE TITLE
Maven  publication required some environment variables set on Github Action CI .

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/java-libkiwix#21]
###  **We have to set some environment variables for publication task.**
     i) OSSRH_USERNAME = this is MavenCentral user name.
     ii) OSSRH_PASSWORD  = this is MavenCentral password.
     iii) SIGNING_KEY_ID = the ID of the GPG key pair, the last eight characters of its fingerprint.
     iv) SIGNING_PASSWORD = the passphrase password of the key pair.
     v) SIGNING_KEY = the base64 encoded private key.
     vi) SONATYPE_STAGING_PROFILE_ID = this is sonatype stagging profile id we can get it from MavenCentral account.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

I have already shared this information with you via email sometimes back.

**Comment by kelson42** [comment]
@MohitMaliFtechiz what is the status here?

**Comment by MohitMaliFtechiz** [comment]
@kelson42, @mgautierfr set the environment variables in GitHub action, and now our CI is successfully publishing the `.aar` file on Maven.
