### ISSUE TITLE
Android apps should catch & handle JNI crashes as exception

### ISSUE THREAD

**Issue by mhutti1** [kiwix/java-libkiwix#24]
_From @kelson42 on September 26, 2016 10:57_

To avoid any wild crashes of the apps. Here is a how to:
http://blog.httrack.com/blog/2013/08/23/catching-posix-signals-on-android/

_Copied from original issue: kiwix/kiwix#330_

**Comment by kelson42** [comment]
@mgautierfr @MohitMaliFtechiz This has to be fixed in new JNI binding. What is the status?
