### ISSUE TITLE
Introduce Kiwix Android `.aar` automated testing to libkiwix automated framework

### ISSUE THREAD

**Issue by kelson42** [kiwix/java-libkiwix#3]
Following discussion in https://github.com/kiwix/kiwix-build/issues/346 it became clear that this would be an added value to be able to fully validate (so Android version of the libkiwix too) automatically and within kwix-lib repo.

**Comment by kelson42** [comment]
@mgautierfr @MohitMaliFtechiz I guess this has been done meanwhile or do we still have old test cases of the libkiwix binding which are still not activated here in this repo?

**Comment by mgautierfr** [comment]
The discussion in https://github.com/kiwix/kiwix-build/issues/346 is pretty old so I don't remember exactly what we expect from `aar` automated testing. But:
- java-libkiwix now has test of the wrapper. Those tests are run in the CI and can be run locally.
- java-libkiwix gradle is creating a aar locally and can upload (through the CI) to maven.

So I suspect we are ok and we can close this issue.
If something is missing, the best will be to open a specific issue with a more specific description of the problem and what to do.
