### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by kelson42** [kiwix/java-libkiwix#50]
It should better include:
* A badge to latest CI run
* An stub example how to use the library

**Comment by kelson42** [comment]
Mostly done with #55 

@MohitMaliDeveloper Can you please put a simple example in Kotlin how to load a zim file and an article? i have also a question: can this lib be used in a normal java program on linux?

**Comment by mgautierfr** [comment]
>  can this lib be used in a normal java program on linux?

Not tested, but I would say mostly.

The only dependency to android is in :
https://github.com/kiwix/java-libkiwix/blob/main/lib/src/main/java/org/kiwix/libkiwix/JNIKiwix.java

But we may have to fix few small things before having a truly java library (compilation, ...)
