### ISSUE TITLE
Implement binding to libkiwix bookmark saving/reading primitives

### ISSUE THREAD

**Issue by kelson42** [kiwix/java-libkiwix#57]
This is necessary for Kiwix Android 3.8.0 ticket https://github.com/kiwix/kiwix-android/issues/3105

**Comment by mgautierfr** [comment]
This is already done (although not tested in the CI):
- https://github.com/kiwix/java-libkiwix/blob/main/lib/src/main/java/org/kiwix/libkiwix/Library.java#L45
- https://github.com/kiwix/java-libkiwix/blob/main/lib/src/main/java/org/kiwix/libkiwix/Library.java#L57-L59
- https://github.com/kiwix/java-libkiwix/blob/main/lib/src/main/java/org/kiwix/libkiwix/Manager.java#L58
