### ISSUE TITLE
`Manager` is unable to read the bookmarks from file.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/java-libkiwix#69]
`Manager` is unable to read the bookmarks from the file if we have not added the `book` to the library for which book we have saved the bookmarks in that file.

e.g. First I added two books to the library and saved some bookmarks to a file and after that, I closed the application, now I reopened the application and tried to load the bookmarks from that file but it did not read any bookmarks from this file, and return nothing, but if I again add same book to the library then it starts reading the bookmarks from that file for this added book but still not reading the other bookmarks which we had saved for other books. But here it should read all the bookmarks from the file without adding the book to the library as bookmarks are independent.

**Steps to reproduce the behavior**
* Add a book to the library.
* Try to save the bookmark in the library.
* Save the bookmarks in a file.
* Create a new library and manager objects.
* Try to read the bookmarks from the saved file.
* You will see it is unable to read the bookmarks from that file.

you can add these test cases in the `test.java` class for testing, create a `bookmark.txt` file inside test package add these bookmarks to that file, and run the test cases.

```
<bookmarks>
  <bookmark>
    <book>
      <id>8a3066ca-b324-b8ef-3e70-ef944b1a22a3</id>
      <title>Alpine Linux Wiki</title>
      <language>eng</language>
      <date>2022-10-17</date>
    </book>
    <title>Alpine Linux Wiki</title>
    <url>https://bookmarkurl.com/</url>
  </bookmark>
</bookmarks>
```

```
 @Test
    public void testSavedBookMarks() throws Exception, ZimFileFormatException, JNIKiwixException {
        TestLibrary lib = new TestLibrary();
        TestManager manager = new TestManager(lib);
        boolean isReaded = manager.readBookmarkFile("bookmark.txt");
        assertEquals(true, isReaded);
        TestBookmark[] bookmarkArray = lib.getBookmarks(true);
        assertEquals(1, bookmarkArray.length);
    }
```

**Comment by MohitMaliFtechiz** [comment]
My bad! This is the libkiwix feature for only getting the current zim file bookmarks `lib.getBookmarks(true);` we we paas `false` then it start reading the full bookmark file.

**Comment by mgautierfr** [comment]
> for only getting the current zim file bookmarks

This is not exactly true.
`true` means that it only return "valid" bookmarks. In this context, a bookmark is considered valid if it is about a book actually stored in the library.
As you create a new library without books, there is no valid bookmark.
